version: 0.0
os: linux

files:
  - source: / # Root of the build artifact from CodeBuild
    destination: /var/www/html # Replace with your Nginx document root

hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root

